from __future__ import annotations

import json
from pathlib import Path

import pytest
import torch

import scripts.research_drl_adaptive_allocator_v1 as allocator
from scripts import research_drl_regime_allocator_v3 as candidate


ROOT = Path(__file__).resolve().parents[1]


def test_regime_candidate_configuration_is_lgbm_biased_and_annealed() -> None:
    assert candidate.INITIAL_TREND_WEIGHT == pytest.approx(0.40)
    assert candidate.INITIAL_LGBM_WEIGHT == pytest.approx(0.60)
    assert candidate.PRIOR_TREND_WEIGHT_START == pytest.approx(0.40)
    assert candidate.PRIOR_TREND_WEIGHT_END == pytest.approx(0.50)
    assert candidate.PRIOR_ANNEAL_EVENTS == 24
    assert candidate.TREND_INCREASE_SMOOTHING_RISK_ON > 0.35
    assert candidate.TREND_DECREASE_SMOOTHING < 0.35


def test_risk_on_increase_is_faster_than_risk_off_increase() -> None:
    original = (
        allocator.ACTION_SMOOTHING_UP,
        allocator.ACTION_SMOOTHING_DOWN,
        allocator.PRIOR_TARGET_BLEND,
    )
    try:
        allocator.ACTION_SMOOTHING_UP = 0.70
        allocator.ACTION_SMOOTHING_DOWN = 0.25
        allocator.PRIOR_TARGET_BLEND = 0.0
        latent = torch.tensor([5.0, 0.0])
        previous = torch.tensor([0.40, 0.40])
        risk_on = allocator.map_and_smooth_action(
            latent, previous, risk_on=torch.tensor(True)
        )
        risk_off = allocator.map_and_smooth_action(
            latent, previous, risk_on=torch.tensor(False)
        )
        assert risk_on[0] > risk_off[0]
    finally:
        (
            allocator.ACTION_SMOOTHING_UP,
            allocator.ACTION_SMOOTHING_DOWN,
            allocator.PRIOR_TARGET_BLEND,
        ) = original


def test_annealed_prior_moves_from_40_to_50_percent_trend() -> None:
    original = (
        allocator.PRIOR_TARGET_BLEND,
        allocator.PRIOR_TREND_WEIGHT_START,
        allocator.PRIOR_TREND_WEIGHT_END,
        allocator.PRIOR_ANNEAL_EVENTS,
    )
    try:
        allocator.PRIOR_TARGET_BLEND = 1.0
        allocator.PRIOR_TREND_WEIGHT_START = 0.40
        allocator.PRIOR_TREND_WEIGHT_END = 0.50
        allocator.PRIOR_ANNEAL_EVENTS = 24
        latent = torch.zeros(2)
        previous = torch.tensor([0.40, 0.40])
        start = allocator.map_and_smooth_action(
            latent, previous, smoothing=1.0, decision_number=0
        )
        mature = allocator.map_and_smooth_action(
            latent, previous, smoothing=1.0, decision_number=24
        )
        assert start[0] == pytest.approx(0.40)
        assert mature[0] == pytest.approx(0.50)
    finally:
        (
            allocator.PRIOR_TARGET_BLEND,
            allocator.PRIOR_TREND_WEIGHT_START,
            allocator.PRIOR_TREND_WEIGHT_END,
            allocator.PRIOR_ANNEAL_EVENTS,
        ) = original


def test_regime_candidate_artifact_preserves_production_gate() -> None:
    path = ROOT / "data" / "drl_regime_allocator_v3.json"
    if not path.exists():
        pytest.skip("v3 artifact is generated by the walk-forward research script")
    payload = json.loads(path.read_text(encoding="utf-8"))
    configuration = payload["configuration"]
    assert configuration["initial_lgbm_weight"] == pytest.approx(0.60)
    assert configuration["prior_target_blend"] == pytest.approx(0.25)
    assert configuration["prior_anneal_events"] == 24
    assert configuration["trend_weight_increase_smoothing_risk_on"] == pytest.approx(0.70)
    assert configuration["trend_weight_decrease_smoothing"] == pytest.approx(0.25)
    assert payload["production_change"] is False
