from __future__ import annotations

import json
from pathlib import Path

import pytest

from scripts import research_drl_lgbm_biased_allocator_v2 as candidate


ROOT = Path(__file__).resolve().parents[1]


def test_lgbm_biased_initial_allocation_is_valid() -> None:
    assert candidate.INITIAL_TREND_WEIGHT == pytest.approx(0.40)
    assert candidate.INITIAL_LGBM_WEIGHT == pytest.approx(0.60)
    assert candidate.INITIAL_LGBM_WEIGHT > candidate.INITIAL_TREND_WEIGHT
    assert candidate.TREND_WEIGHT_MIN <= candidate.INITIAL_TREND_WEIGHT
    assert candidate.INITIAL_TREND_WEIGHT <= candidate.TREND_WEIGHT_MAX


def test_lgbm_biased_candidate_preserves_fixed_75_25_comparison() -> None:
    path = ROOT / "data" / "drl_lgbm_biased_allocator_v2.json"
    if not path.exists():
        pytest.skip("v2 artifact is generated by the walk-forward research script")
    payload = json.loads(path.read_text(encoding="utf-8"))
    configuration = payload["configuration"]
    assert configuration["initial_trend_weight"] == pytest.approx(0.40)
    assert configuration["initial_lgbm_weight"] == pytest.approx(0.60)
    assert configuration["static_baseline_trend_weight"] == pytest.approx(0.75)
    assert configuration["static_baseline_lgbm_weight"] == pytest.approx(0.25)
    assert payload["production_change"] is False
